name: ci

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.21', '1.22' ]

    env:
      TESTCONTAINERS_RYUK_DISABLED: "false"
      RYUK_CONNECTION_TIMEOUT: "60s"
      RYUK_RECONNECTION_TIMEOUT: "10s"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup rootless Docker
        uses: ScribeMD/rootless-docker@0.2.2

      - name: Remove Docker root socket
        run: sudo rm -rf /var/run/docker.sock

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: "go.sum"

      - name: Test
        timeout-minutes: 20
        run: |
          go test -v ./...